[env]
docargs = "doc|--quiet|--no-deps|--target=${@}"

[tasks.fixfmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.update]
command = "cargo"
args = ["update"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--no-deps", "--all-features"]

[tasks.fixclippy]
command = "cargo"
install_crate = "clippy"
args = ["clippy", "--no-deps", "--all-targets", "--all-features", "--fix"]

[tasks.docpublic]
command = "cargo"
args = ["@@split(docargs,|)"]

[tasks.docprivate]
command = "cargo"
args = ["@@split(docargs,|)", "--document-private-items"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.build]
description = "Build everything"
category = "Build"
command = "cargo"
args = ["build"]

[tasks.buildrelease]
description = "Build everything in release mode"
category = "Build"
command = "cargo"
args = ["build", "--release"]

[tasks.clean]
description = "Clean everything"
category = "Clean"
command = "cargo"
args = ["clean"]

[tasks.releasecheck]
dependencies = ["fixclippy", "fixfmt", "update"]

[tasks.publish]
dependencies = ["releasecheck"]
command = "cargo"
args = ["publish"]

[tasks.publishdry]
extend = "publish"
args = ["publish", "--dry-run"]